project:
  type: website
  output-dir: publish-final

website:
  title: "Articles"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    html-math-method: mathjax
    embed-resources: false
